# db_file_user.toml: mysql数据库db_file_user配置文件

# Service的名字, 必选
Name = "db_file_user"

## 各种自定义的参数, 非必选
# 写数据超时 ms
WriteTimeOut = 1000
# 读数据超时 ms
ReadTimeOut = 500
# 请求失败后的重试次数: 总请求次数 = Retry + 1; database/sql 自带两次 retry
# Retry = 2

# 资源定位: 手动配置 - 使用IP、端口
[Resource.Manual]
Host = "rm-bp17lvq049ft85ht1ao.mysql.rds.aliyuncs.com"
Port = 3306

# mysql组件配置
[MySQL]
Username = "gin_file_download_user"
Password = ""
DBName = "db_file_user"
DBDriver = "mysql"
Charset = "utf8"
Collation = "utf8_unicode_ci"
Timeout = 90000 # ms
SQLLogLen = -1 # 打印sql内容, 为0不打印, -1 为全部